// examples/wirestate-react-lit-mobx/src/components/QueriesData.tsx
import "./QueriesData.css";

import { QueryBus } from "@wirestate/core";
import { useInjection, useOnQuery } from "@wirestate/react";
import { useCallback, useState } from "react";

import { EGlobalQuery } from "@/constants/queries";
import { ECounterServiceQuery, type ICounterSnapshot, type ICounterSummary } from "@/services/CounterService.query";
import { LoggerService } from "@/services/LoggerService";
import { ThemeService } from "@/services/ThemeService";
import { type Optional, type Theme } from "@/types";

export function QueriesData() {
  const [snapshot, setSnapshot] = useState<Optional<ICounterSnapshot>>(null);
  const [summary, setSummary] = useState<Optional<ICounterSummary>>(null);

  const queryBus: QueryBus = useInjection(QueryBus);
  const loggerService: LoggerService = useInjection(LoggerService);
  const themeService: ThemeService = useInjection(ThemeService);

  const onPullSummary = useCallback(() => {
    const value: ICounterSummary = queryBus.query<ICounterSummary>(ECounterServiceQuery.GET_COUNTER_SUMMARY, {
      value: "some-data",
    });

    setSummary(value);
  }, [queryBus]);

  const onFetchSnapshot = useCallback(async () => {
    const value: ICounterSnapshot = await queryBus.queryAsync<ICounterSnapshot>(
      ECounterServiceQuery.FETCH_COUNTER_SNAPSHOT,
    );

    setSnapshot(value);

    loggerService.log(`[QueriesData] Fetched snapshot:`, value);
  }, [loggerService, queryBus]);

  useOnQuery<Theme>(EGlobalQuery.GET_ACTIVE_THEME, () => themeService.theme);

  return (
    <div className={"queries"}>
      <div className={"query-controls"}>
        <button className={"counter ghost"} onClick={onPullSummary}>
          Query summary (sync)
        </button>

        <button className={"counter ghost"} onClick={onFetchSnapshot}>
          Fetch snapshot (async)
        </button>
      </div>

      {summary ? (
        <p className={"query-result"}>
          Summary — count: <strong>{summary.count}</strong>, parity: <strong>{summary.isEven ? "even" : "odd"}</strong>
        </p>
      ) : null}

      {snapshot ? (
        <p className={"query-result"}>
          Snapshot — count: <strong>{snapshot.count}</strong>, fetched at:{" "}
          <strong>{new Date(snapshot.fetchedAt).toLocaleTimeString()}</strong>
        </p>
      ) : null}
    </div>
  );
}

// examples/wirestate-lit-signals/src/components/queries-data.ts
import { QueryBus } from "@wirestate/core";
import { injection } from "@wirestate/lit";
import { html, LitElement, CSSResult, css } from "lit";
import { customElement, state } from "lit/decorators.js";

import { ECounterServiceQuery, ICounterSnapshot } from "@/services/CounterService.query";
import { LoggerService } from "@/services/LoggerService";
import { resetStyles } from "@/styles/reset";
import { Optional } from "@/types";

@customElement("w-queries-data")
export class QueriesData extends LitElement {
  public static styles: Array<CSSResult> = [
    resetStyles,
    css`
      :host {
        h3 {
          color: var(--accent);
        }

        .summaries {
          display: flex;
          flex-direction: column;
          gap: var(--space-2);
          margin: var(--space-2) 0;
          font-size: var(--text-sm);
        }

        .summary-paragraph {
          padding: var(--space-2);
          border: 1px solid var(--accent);
        }

        .control {
          font-size: 16px;
          padding: 5px 10px;
          border-radius: 5px;
          color: var(--accent);
          background: var(--accent-bg);
          border: 2px solid transparent;
          transition:
            border-color 0.3s,
            background 0.3s;
          cursor: pointer;

          &:hover {
            border-color: var(--accent-border);
          }

          &:focus-visible {
            outline: 2px solid var(--accent);
            outline-offset: 2px;
          }
        }
      }
    `,
  ];

  @injection(QueryBus)
  private readonly queryBus!: QueryBus;

  @injection(LoggerService)
  private readonly loggerService!: LoggerService;

  @state()
  private snapshot: Optional<ICounterSnapshot> = null;

  @state()
  private summary: Optional<ICounterSnapshot> = null;

  public async onQuerySummary(): Promise<void> {
    this.summary = await this.queryBus.query(ECounterServiceQuery.GET_COUNTER_SUMMARY, { value: "some-data" });
  }

  public async onQuerySnapshot(): Promise<void> {
    this.snapshot = await this.queryBus.queryAsync<ICounterSnapshot>(ECounterServiceQuery.FETCH_COUNTER_SNAPSHOT);
  }

  public render() {
    return html`
      <div class="query-controls">
        <button class="control" @click="${() => this.onQuerySummary()}">Query summary (sync)</button>
        <button class="control" @click="${() => this.onQuerySnapshot()}">Fetch snapshot (async)</button>
      </div>

      <div class="summaries">
        ${this.summary
          ? html`<p class="summary-paragraph">
              <span>Summary — count:</span> <strong>${this.summary.count}</strong>

              <span>Last incremented at:</span> <strong>${this.summary.lastIncrementedAt}</strong>
            </p>`
          : null}

        <!-- -->

        ${this.snapshot
          ? html`<p class="summary-paragraph">
              <span>Summary — count:</span> <strong>${this.snapshot.count}</strong>

              <span>Last incremented at:</span> <strong>${this.snapshot.lastIncrementedAt}</strong>
              <span>Fetched at:</span> <strong>${this.snapshot.fetchedAt}</strong>
            </p>`
          : null}
      </div>
    `;
  }
}
