// src/wirestate-lit/provision/container-provider.ts
import { ContextProvider } from "@lit/context";
import { type ReactiveController, type ReactiveControllerHost } from "@lit/reactive-element";
import { type ContainerConfig, Container, WirestateError, validateContainerConfig } from "@wirestate/core";

import { ContainerContext } from "../context/container-context";
import { ERROR_CODE_INVALID_ARGUMENTS } from "../error/error-code";
import { type Maybe } from "../types/general";

/**
 * Describes options for {@link ContainerProvider}.
 *
 * @remarks
 * Pass either `container` or `config`. Passing both is an error.
 *
 * @group Provision
 */
export interface ContainerProviderOptions {
  /**
   * External container instance to provide as-is.
   *
   * @remarks
   * External containers are never activated, recreated, or disposed by this
   * provider. They are published through context while the host is connected.
   * Provider lifecycle hooks run while the host is connected.
   */
  readonly container?: Container;

  /**
   * Managed container creation options.
   *
   * @remarks
   * The managed container is created when the host connects, disposed when it
   * disconnects, and recreated on the next reconnect. Managed containers
   * activate all bindings by default unless `activate` is provided explicitly.
   * The provider value is `undefined` while the host is disconnected.
   */
  readonly config?: ContainerConfig;
}

/**
 * Reactive controller that provides a root container through Lit context.
 *
 * @remarks
 * Two modes:
 *
 * - External `container`: published while connected, provisioned, never disposed.
 * - Managed `config`: created on connect, provisioned, disposed on disconnect.
 *
 * Managed containers activate all bindings by default. Before connect and after
 * disconnect, the context value is `undefined`.
 *
 * @group Provision
 *
 * @example
 * ```typescript
 * import { Injectable } from "@wirestate/core";
 * import { ContainerProvider } from "@wirestate/lit";
 * import { LitElement } from "lit";
 *
 * @Injectable()
 * class CounterService {}
 *
 * class AppRoot extends LitElement {
 *   private readonly provider = new ContainerProvider(this, {
 *     config: { bindings: [CounterService] },
 *   });
 * }
 * ```
 */
export class ContainerProvider<E extends ReactiveControllerHost & HTMLElement = ReactiveControllerHost & HTMLElement>
  extends ContextProvider<typeof ContainerContext, E>
  implements ReactiveController
{
  protected config: Maybe<ContainerConfig>;
  protected container: Maybe<Container>;

  /**
   * @param host - The host element.
   * @param options - Provisioning options.
   * @param options.container - External container instance to provide.
   * @param options.config - Managed container creation config.
   */
  public constructor(host: E, options: ContainerProviderOptions) {
    if (!options.container && !options.config) {
      throw new WirestateError(
        "ContainerProvider requires a valid container instance or creation config.",
        ERROR_CODE_INVALID_ARGUMENTS
      );
    } else if (options.container && options.config) {
      throw new WirestateError(
        "ContainerProvider requires only container or valid config object to be provided.",
        ERROR_CODE_INVALID_ARGUMENTS
      );
    } else if (options.config) {
      validateContainerConfig(options.config);
    } else if (!(options.container instanceof Container)) {
      throw new WirestateError(
        "ContainerProvider requires a valid container instance or creation config.",
        ERROR_CODE_INVALID_ARGUMENTS
      );
    }

    super(host, { context: ContainerContext });

    this.config = options.config ? { ...options.config, activate: options.config.activate ?? true } : null;
    this.container = options.container;
  }

  public hostConnected(): void {
    const container: Container = this.config
      ? (this.container = new Container(this.config))
      : (this.container as Container);

    try {
      container.provision();

      super.setValue(container);
      super.hostConnected();
    } catch (error) {
      if (this.config) {
        this.destroyManagedContainer(container);
      } else {
        // Expect container to be deprovisioned by this moment, but leaving deprovision as explicit operation.
        container.deprovision();
      }

      throw error;
    }
  }

  public hostDisconnected(): void {
    const container: Container = this.container as Container;

    if (this.config) {
      this.destroyManagedContainer(container);
    } else {
      container.deprovision();
    }

    this.clearCallbacks();
    super.setValue(undefined as unknown as Container);
  }

  public setValue(container: Container, force?: boolean): void {
    if (this.config) {
      throw new WirestateError(
        "ContainerProvider owns managed containers. Use `setConfig(config)` to replace the managed container.",
        ERROR_CODE_INVALID_ARGUMENTS
      );
    }

    const previous: Maybe<Container> = this.container;

    this.container = container;

    if (this.host.isConnected) {
      if (Object.is(previous, container)) {
        super.setValue(container, force);
      } else {
        if (previous) {
          previous.deprovision();
        }

        try {
          container.provision();

          super.setValue(container, force);
        } catch (error) {
          // Expect container to be deprovisioned by this moment, but leaving deprovision as explicit operation.
          container.deprovision();

          throw error;
        }
      }
    }
  }

  /**
   * Replaces the managed container config.
   *
   * @remarks
   * External-container providers cannot switch to managed mode. Connected
   * managed providers replace the current container immediately. Disconnected
   * managed providers store the config for the next connection.
   *
   * @param config - Container creation options to use from now on.
   */
  public setConfig(config: ContainerConfig): void {
    if (!this.config) {
      throw new WirestateError(
        "ContainerProvider uses an external container. Use `setValue(container)` to replace it.",
        ERROR_CODE_INVALID_ARGUMENTS
      );
    }

    validateContainerConfig(config);

    this.config = { ...config, activate: config.activate ?? true };

    if (this.host.isConnected) {
      if (this.container) {
        this.destroyManagedContainer(this.container);
      }

      const container: Container = new Container(this.config);

      this.container = container;

      try {
        container.provision();

        super.setValue(container);
      } catch (error) {
        this.destroyManagedContainer(container);

        throw error;
      }
    }
  }

  /**
   * Destroys the currently owned managed container.
   *
   * @param container - Managed container to deprovision and dispose.
   */
  protected destroyManagedContainer(container: Container): void {
    container.deprovision();

    this.container = null;

    container.unbindAll();
  }
}

// src/wirestate-react/provision/container-provider.ts
import { type ContainerConfig, Container, WirestateError } from "@wirestate/core";
import { type ReactElement, type ReactNode, createElement, useEffect, useRef, useState } from "react";

import { ContainerContext } from "../container/container-context";
import { ERROR_CODE_INVALID_ARGUMENTS } from "../error/error-code";
import { type Maybe, type Nullable } from "../types/general";

import {
  type ReactContainerProvisionLifecycle,
  retainContainer,
  scheduleContainerDestruction,
} from "./provision-lifecycle";

/**
 * Describes props for {@link ContainerProvider}.
 *
 * @remarks
 * Pass either `container` or `config`. Passing both is an error.
 *
 * @group Provision
 */
export interface ContainerProviderProps {
  /**
   * External container instance to provide as-is.
   *
   * @remarks
   * External container instances are provisioned by this provider, but never
   * disposed.
   */
  readonly container?: Container;

  /**
   * Managed container creation options.
   *
   * @remarks
   * Managed containers created from config are disposed on unmount and activate
   * all bindings by default unless `activate` is provided explicitly. The config
   * is read once when the provider mounts: later changes are ignored. Pass a
   * React `key` to the provider to recreate the container.
   */
  readonly config?: ContainerConfig;

  /**
   * React subtree that receives the active container.
   */
  readonly children?: ReactNode;
}

/**
 * Captures a provider provision failure so it can be thrown from render.
 */
interface ContainerProvisionError {
  readonly error: unknown;
}

/**
 * Provides a root Wirestate container to a React subtree.
 *
 * @remarks
 * Two modes:
 *
 * - External `container`: passed through, provisioned, never disposed.
 * - Managed `config`: created by the provider, provisioned, disposed on unmount.
 *
 * Managed containers activate all bindings by default. Pass `activate: false`
 * to keep them lazy.
 *
 * Managed config is construction-only: it is read once when the provider
 * mounts, and later changes are ignored. Pass a React `key` to the provider
 * to recreate the container explicitly.
 *
 * @group Provision
 *
 * @param props - Provider props.
 * @returns React context provider for the active container.
 * @throws `WirestateError` if props are invalid or provider mode changes.
 *
 * @example
 * ```tsx
 * import { Injectable } from "@wirestate/core";
 * import { ContainerProvider } from "@wirestate/react";
 * import { useMemo } from "react";
 *
 * @Injectable()
 * class CounterService {}
 *
 * export function Application() {
 *   const config = useMemo(() => ({ bindings: [CounterService] }), []);
 *
 *   return (
 *     <ContainerProvider config={config}>
 *       <Counter />
 *     </ContainerProvider>
 *   );
 * }
 * ```
 */
export function ContainerProvider(props: ContainerProviderProps): ReactElement {
  const configValue: unknown = props.config;
  const hasConfig: boolean = configValue !== undefined;

  if (hasConfig && (configValue === null || typeof configValue !== "object" || Array.isArray(configValue))) {
    throw new WirestateError(
      "ContainerProvider requires a valid container instance or creation config.",
      ERROR_CODE_INVALID_ARGUMENTS
    );
  } else if (!props.container && !hasConfig) {
    throw new WirestateError(
      "ContainerProvider requires a valid container instance or creation config.",
      ERROR_CODE_INVALID_ARGUMENTS
    );
  } else if (props.container && hasConfig) {
    throw new WirestateError(
      "ContainerProvider requires only container or valid config object to be provided.",
      ERROR_CODE_INVALID_ARGUMENTS
    );
  } else if (props.container !== undefined && !(props.container instanceof Container)) {
    throw new WirestateError(
      "ContainerProvider requires a valid container instance or creation config.",
      ERROR_CODE_INVALID_ARGUMENTS
    );
  }

  const managedSource: Maybe<ContainerConfig> = props.config;
  const externalContainer: Maybe<Container> = props.container;
  const owned: boolean = Boolean(managedSource);
  const ownedRef = useRef<boolean>(owned);

  const pendingDestructionRef = useRef<Nullable<ReactContainerProvisionLifecycle>>(null);

  const [error, setError] = useState<Nullable<ContainerProvisionError>>(null);
  const [managedContainer] = useState<Nullable<Container>>(() =>
    managedSource ? new Container({ ...managedSource, activate: managedSource.activate ?? true }) : null
  );

  if (ownedRef.current !== owned) {
    throw new WirestateError(
      "ContainerProvider cannot switch between external and managed container modes. Pass a React key to remount the provider.",
      ERROR_CODE_INVALID_ARGUMENTS
    );
  }

  const activeContainer: Container = managedContainer ?? (externalContainer as Container);

  useEffect(() => {
    const pendingDestruction: ReactContainerProvisionLifecycle = (pendingDestructionRef.current ??= new Map());

    retainContainer(activeContainer, pendingDestruction);

    try {
      activeContainer.provision();
    } catch (error) {
      if (owned) {
        scheduleContainerDestruction(activeContainer, pendingDestruction);
      } else {
        // Expect container to be deprovisioned by this moment, but leaving deprovision as explicit operation.
        activeContainer.deprovision();
      }

      setError({ error });

      return;
    }

    return () => {
      if (owned) {
        scheduleContainerDestruction(activeContainer, pendingDestruction);
      } else {
        activeContainer.deprovision();
      }
    };
  }, [activeContainer, owned]);

  if (error) {
    throw error.error;
  }

  return createElement(ContainerContext.Provider, { value: activeContainer }, props.children ?? null);
}
